app/org/hadatac/console/http/GetSolrQuery.java
app/org/hadatac/console/http/JsonHandler.java
app/org/hadatac/console/models/SpatialQueryResults.java
app/org/hadatac/console/views/bootstrap3/checkboxes.scala.html
app/org/hadatac/console/views/fieldset.scala.html
app/org/hadatac/console/views/index_browser.scala.html
app/org/hadatac/console/views/measurement_details.scala.html
app/org/hadatac/console/views/table.scala.html
app/org/hadatac/data/loader/ccsv/Parser.java
app/org/hadatac/entity/pojo/Measurement.java
build.sbt
project/plugins.sbt
solr/solr-home/measurement/conf/schema.xml

Load into master the measurement browser.

Data loader

---

app/org/hadatac/console/controllers/Detector.java
app/org/hadatac/console/controllers/DetectorList.java
app/org/hadatac/console/http/GetSparqlQuery.java
app/org/hadatac/console/views/detector_browser.scala.html
app/org/hadatac/console/views/entity_browser.scala.html
app/org/hadatac/console/views/entitycharacteristic_browser.scala.html
app/org/hadatac/console/views/hierarchy_browser.scala.html
app/org/hadatac/console/views/main.scala.html
app/org/hadatac/console/views/metadata_navigation.scala.html
app/org/hadatac/console/views/print_characteristic_entry.scala.html
app/org/hadatac/console/views/print_detector_entry.scala.html
app/org/hadatac/console/views/print_detector_model_entry.scala.html
app/org/hadatac/console/views/print_entity_entry.scala.html
app/org/hadatac/console/views/print_instrument_entry.scala.html
app/org/hadatac/console/views/print_instrument_model_entry.scala.html
app/org/hadatac/console/views/print_platform_entry.scala.html
app/org/hadatac/console/views/print_platform_model_entry.scala.html
app/org/hadatac/console/views/print_unit_entry.scala.html
public/css/printfriendly.css

in preparation for metadata review. Closes #28.

printer-friendly versions of metadata browser lists added

---

app/org/hadatac/console/http/GetSparqlQuery.java
app/org/hadatac/console/models/SparqlQueryResults.java
app/org/hadatac/console/models/TripleDocument.java
public/css/main.css

I found a few small errors in the sparql queries and result handling and fixed them. The changes should resolve issue #45

fixed bug in SPARQL result handling that should solve #45

---

app/org/hadatac/console/controllers/triplestore/DiffTool.java
app/org/hadatac/console/views/triplestore/diff_results.scala.html
app/org/hadatac/console/views/triplestore/getLabkeyFolders.scala.html
conf/routes

Looking to merge initial commit of difference tool. Code has been compiled successfully on sbt before branching.

Diff Tool commit 1, headers only version

---

deploy_hadatac.sh

"-p" --> mode, ownership, timestamps

Preserve permissions when copying config, also copy mine.conf

---

app/com/google/refine/clustering/binning/FingerprintKeyer.java
app/com/google/refine/clustering/binning/Keyer.java
app/org/hadatac/console/controllers/metadata/TermOverlap.java
app/org/hadatac/console/views/metadata/searchTermOverlap.scala.html
app/org/hadatac/utils/OntologyTerm.java
app/org/hadatac/utils/TermClusteror.java
conf/routes

Added Overlapping terms view that clusters similar ontology terms at:
http://localhost:9000/hadatac/metadata/termOverlap

Browse graph

---

app/org/hadatac/console/models/OtMSparqlQueryResults.java
app/org/hadatac/console/views/metadata/browseKnowledgeGraph.scala.html
app/org/hadatac/utils/Hierarchy.java

Two small bugs that I believe are unrelated to the code I wrote: 
1) sio displayes three additional top level elements but the problem looks like it originates from the query results
2) prov does not display anything but it does return the correct tree mapping, unclear why it isn't displaying

reworked ontology browser code

---

app/org/hadatac/console/controllers/annotator/AutoAnnotator.java
app/org/hadatac/console/controllers/dataacquisitionsearch/Downloader.java
app/org/hadatac/console/controllers/fileviewer/DDEditor.java
app/org/hadatac/console/controllers/fileviewer/DataDictionaryAnnotator.java
app/org/hadatac/console/controllers/fileviewer/SDDEditorV2.java
app/org/hadatac/console/controllers/workingfiles/FileHeadersIntoSDD.java
app/org/hadatac/console/controllers/workingfiles/WorkingFiles.java
app/org/hadatac/console/views/annotator/annotation_log.scala.html
app/org/hadatac/console/views/fileviewer/dd_editor.scala.html
app/org/hadatac/console/views/fileviewer/sdd_editor_v2.scala.html
app/org/hadatac/console/views/metadata/browseKnowledgeGraph.scala.html
app/org/hadatac/console/views/workingfiles/fileHeadersIntoSDD.scala.html
app/org/hadatac/console/views/workingfiles/workingFiles.scala.html
app/org/hadatac/data/loader/SpreadsheetRecordFile.java
app/org/hadatac/entity/pojo/SDD.java
conf/routes
public/javascripts/treeEntity.js
public/sheetjs/css/sheet2js.css
public/sheetjs/js/load_from_server.js
public/sheetjs/js/load_from_server2.js
public/sheetjs/js/load_from_server_dd.js
public/sheetjs/js/sddValidation.js

Fixed sdd validation, removed redundancy, updated buttons, added populate sdd from dd.

SDD Editor update 3

---

create_namespaces.sh
install_hadatac.sh
solr/run_solr6.sh
solr/solr6.in.sh

Break installation script if zip is missing
Ran dos2unix on file to remove windows line endings

Address installation script issues

---

uninstall.sh

Added an uninstall script

---

app/org/hadatac/utils/ConfigProp.java
build.sbt
conf/hadatac.conf
test/SeleniumTest.java
test/controllers/UserAuthTest.java

This update enables selenium UI testing, showcases an initial selenium test, and updates hadatac.config to support testing on multiple platforms and setups.

Selenium Update

---

app/org/hadatac/entity/pojo/Measurement.java

This is to fix the "shifting issue" discovered by Jeanette from 2016-1762. Tested in local and seems to be working fine.

fix the shifting issue

---

app/org/hadatac/entity/pojo/Alignment.java

this is the "sibling has multiple values" issue discovered by Jeanette when downloading a lab file. The fix is in the actual implementation of the upstream+downstream phase of the algorithm proposed/implemented by Paulo.

fix the latest sibling issue found by Jeanette in the lab files

---

app/org/hadatac/console/providers/MyUsernamePasswordAuthProvider.java
app/org/hadatac/console/views/account/signup/email/invitation_email_en.scala.html

This is to change the validation email text and settings. thanks.

this is to change the validation email

---

conf/hadatac.conf

added a few parameters to hadatac.conf for invitation email settings

added a few parameters to hadatac.conf for invitation email settings

---

app/org/hadatac/console/views/dashboard.scala.html
app/org/hadatac/console/views/metadata/metadata.scala.html
app/org/hadatac/console/views/portal.scala.html
public/javascripts/portal-text.js

this includes two fixes:
1. fix the portal text by using javascript
2. hide some content on the metadata browser since they give null-pointers

fix the portal text and hide the metedata browse

---

app/module/DatabaseExecutionContext.java
app/org/hadatac/console/controllers/dataacquisitionsearch/DataAcquisitionSearch.java
app/org/hadatac/entity/pojo/Measurement.java

using concurrency to improve the performance

using concurrency to improve the performance

---

conf/application.conf

this is for the concurrency handling of facet search

change application.conf to add thread pool for concurrency handling of facet search

---

app/module/DatabaseExecutionContext.java
app/org/hadatac/console/controllers/dataacquisitionsearch/DataAcquisitionSearch.java
app/org/hadatac/entity/pojo/Measurement.java
conf/application.conf

This is to merge from `HHEAR` to `HHEAR_release_1220`, to pick up all the performances changes we have done since the last merge.

this is to pick up all the performance related changes we have done

---

app/org/hadatac/console/http/SPARQLUtilsFacetSearch.java

need to reset the pointer back to the beginning of the result set so resultSet.hasNext() can start to read through the result.

need to reset the pointer to the beginning of the stored results

---

app/org/hadatac/console/views/main.scala.html
app/org/hadatac/console/views/maingraph.scala.html
app/org/hadatac/filters/Filters.java
app/org/hadatac/filters/HadatacLoggingFilter.java
conf/application.conf
conf/logback.xml

this is to add application.log and access.log. access.log is created by using Play! filters. Also, both log files are using a daily rollover with compression, and keep for 7 days.

HHEAR-336: add application.log and access.log

---

app/org/hadatac/console/controllers/dataacquisitionsearch/Downloader.java
app/org/hadatac/console/views/dataacquisitionsearch/downloader.scala.html

this is to fix the download progress indicator to make it automatically updated instead of user manually clicking refresh button

fix the download progress indicator to make it automatically updated

---

app/org/hadatac/console/views/account/email/password_reset_en.scala.html
app/org/hadatac/console/views/account/signup/email/verify_email_en.scala.html

this is the fix for the email issue, on release branch only.

fixing the email issue

---

app/org/hadatac/data/loader/MeasurementGenerator.java
app/org/hadatac/entity/pojo/Alignment.java
app/org/hadatac/entity/pojo/Measurement.java

this is to fix the download issue. new entry added to hadatac.conf:
```
download {
alignment="Child,Adult"
}
```
added in hadatac.conf

HHEAR-372: download issue discovered from 1448

---

app/module/OnStart.java

to fix the issue of losing the in-memory model when server restarts: added the in-memory model creation to OnStart.java

in-memory model lost when restart server

---

app/org/hadatac/console/http/SolrSearchProxy.java
public/javascripts/jquery.facetview.js

this is to fix the "filter does not work" issue in study search.

HHEAR-401: fix the study search filter

---

app/org/hadatac/entity/pojo/Variable.java

This is a patch for supporting multiple attributes during Study Search. Will need to put in a long-term solution after discussion.

HHEAR-408: patch for supporting multiple attributes

---

app/org/hadatac/console/views/metadataacquisition/metadataacquisition.scala.html

this is to hide the "download" button in Study Search

HHEAR-239: Enable HADatAc Study Search Feature

---

app/module/OnStart.java
app/org/hadatac/console/controllers/annotator/AutoAnnotator.java
app/org/hadatac/console/controllers/dataacquisitionsearch/DataAcquisitionSearch.java
app/org/hadatac/console/controllers/dataacquisitionsearch/Downloader.java
app/org/hadatac/console/controllers/fileviewer/DDEditor.java
app/org/hadatac/console/controllers/fileviewer/DataDictionaryAnnotator.java
app/org/hadatac/console/controllers/fileviewer/SDDEditor.java
app/org/hadatac/console/controllers/fileviewer/SDDEditorV2.java
app/org/hadatac/console/controllers/triplestore/ExportKB.java
app/org/hadatac/console/controllers/triplestore/LoadOnt.java
app/org/hadatac/console/controllers/workingfiles/FileHeadersIntoSDD.java
app/org/hadatac/console/controllers/workingfiles/Folder.java
app/org/hadatac/console/controllers/workingfiles/NewFile.java
app/org/hadatac/console/controllers/workingfiles/WorkingFiles.java
app/org/hadatac/console/views/dashboard.scala.html
app/org/hadatac/console/views/dataacquisitionsearch/downloader.scala.html
app/org/hadatac/console/views/metadataacquisition/metadataacquisition.scala.html
app/org/hadatac/console/views/portalAdmin.scala.html
app/org/hadatac/console/views/portalNonAdmin.scala.html
app/org/hadatac/console/views/triplestore/clean.scala.html
app/org/hadatac/console/views/workingfiles/workingFiles.scala.html
app/org/hadatac/entity/pojo/DataFile.java
app/org/hadatac/entity/pojo/Measurement.java
app/org/hadatac/utils/ConfigProp.java
app/org/hadatac/utils/FileManager.java
app/org/hadatac/utils/Path.java
conf/routes

so we can take the "download workspace" change + "hide the download button for study search"

This is to merge from HHEAR to HHEAR_release_0121

---

app/org/hadatac/console/controllers/dataacquisitionsearch/Downloader.java
app/org/hadatac/console/views/workingfiles/renameFile.scala.html
app/org/hadatac/console/views/workingfiles/workingFiles.scala.html
app/org/hadatac/entity/pojo/DataFile.java

this is to revert the hack we did, and change the path from DataFile.java. Also change template files to make the display of the path correct (hiding the path before /download)

HHEAR-387: fixing the path and display directory info

---

app/org/hadatac/console/controllers/metadataacquisition/MetadataAcquisition.java

This is to fix the issue that Jeanette has discovered in Study Search, where indicator(s) are missing, such as "Biological Response"

HHEAR-239: fix the problem of missing indicators, such as Biological Response

---

app/org/hadatac/console/controllers/metadataacquisition/MetadataAcquisition.java

fix the display format for Biological Response indictor.

HHEAR-239 fix the display format for Biological Response

---

app/org/hadatac/console/controllers/metadataacquisition/MetadataAcquisition.java
app/org/hadatac/entity/pojo/Pair.java
app/org/hadatac/entity/pojo/Variable.java

this has a few changes: 1. use a List of Pairs to remember <attributeURI, indicatorURI>, 2. use existing FirstLabel.getPrettyLabel() method to retrieve labels at the last step, 3. improved SPARQL query to compute the indicator.

HHEAR-461: Variables in Study Search Only Appear Under One Indicator

---

app/org/hadatac/console/http/ResumableUpload.java
app/org/hadatac/console/models/SysUser.java
app/org/hadatac/console/providers/SimpleTestUsernamePasswordAuthenticator.java
app/org/hadatac/data/loader/DASchemaAttrGenerator.java
app/org/hadatac/entity/pojo/DataAcquisitionSchemaAttribute.java
app/org/hadatac/entity/pojo/Indicator.java
app/org/hadatac/entity/pojo/MeasurementType.java
app/org/hadatac/entity/pojo/SDD.java
app/org/hadatac/entity/pojo/Variable.java
app/org/hadatac/metadata/api/MetadataFactory.java

this includes the changes for both HHEAR-507 and HHEAR-508.

HHEAR-507, HHEAR-508: Fix SDD Ingestion to Correctly Create hasco:hasAttribute Metadata in Graph

---

app/org/hadatac/entity/pojo/Attribute.java
app/org/hadatac/utils/FirstLabel.java

Make the "first label" Method Look First in Preferred Graph

HHEAR-589: Make the first label Method Look First in Preferred Graph

---

app/org/hadatac/data/loader/BaseGenerator.java
app/org/hadatac/data/loader/GeneratorChain.java
app/org/hadatac/data/loader/SSDSampleMapper.java
app/org/hadatac/data/loader/StudyObjectGenerator.java
app/org/hadatac/entity/pojo/HADatAcThing.java

This is to change the way the subject URIs are generated so that studies can share common subjects.

HHEAR-599:Study Subject URIs Should Not Include Study IDD

---

app/org/hadatac/entity/pojo/Measurement.java
app/org/hadatac/entity/pojo/StudyObject.java

this is the fix for dataset generating to support multiple studies for subjects.

HHEAR-645: Update Facet Search Dataset Generation to Support Multiple Studies for Subjects

---

app/org/hadatac/console/controllers/Application.java
app/org/hadatac/console/providers/MyUsernamePasswordAuthProvider.java
conf/hadatac.conf

added enabling https in email links from config

added enabling https in email links from config

---

app/org/hadatac/entity/pojo/Measurement.java

This is to merge into HHEAR_release_2021.4, to fix the missing StudyIDs when doing dataset generations.

HHEAR-737: missing study ID in dataset generation

---

conf/testConfig.json
test/src/studyTest/StudyTest.java

this is what we have for now, still need to make these tests more flexible and more complete. But would like to ask for a merge to HHEAR so we can try these out on dev instance.

HHEAR-231: Develop QC Tests for Generated Datasets from Single DA Files

---

public/javascripts/jquery.facetview.js

This the same merge request as https://github.com/paulopinheiro1234/hadatac/pull/299,  but this one merges into release branch.

HHEAR-815: Determine how to replace default number on Study Search Interface

---

public/javascripts/jquery.facetview.js

This is to merge release back to hhear branch, now that the release is done and stable.

HHEAR-816: merge release branch back to hhear

---

app/org/hadatac/console/controllers/Signup.java

redirecting to a url where user email is hidden

---

app/org/hadatac/console/views/main.scala.html
app/org/hadatac/console/views/maingraph.scala.html

Jquery vulnerability version fix

fixed jquery version vulnerability

---

app/org/hadatac/console/controllers/Signup.java

Added X frames  header to signup

added X frame header t odeny for Signup

---

app/org/hadatac/entity/pojo/User.java

@paulopinheiro1234 can you review and approve pull request.

update user pre-registration to use the store_users graph

---

app/org/hadatac/console/controllers/Signup.java
app/org/hadatac/console/controllers/dataacquisitionsearch/DataAcquisitionSearch.java
app/org/hadatac/console/controllers/dataacquisitionsearch/Downloader.java
app/org/hadatac/console/controllers/studies/StudyView.java
app/org/hadatac/console/providers/MyUsernamePasswordAuthProvider.java
app/org/hadatac/console/views/dataacquisitionsearch/facetOnlyBrowser.scala.html
app/org/hadatac/console/views/receiver.scala.html
app/org/hadatac/console/views/studies/studyView.scala.html
app/org/hadatac/entity/pojo/Measurement.java
public/javascripts/measurement.js

Revamp Study Page.
Changes to rename download files on the download page.
Accept params from HHEAR Portal new Study View Page to do download, show shiny app.
Update the Generate Dataset Method to Use FacetHandler.
Make frequency comma delimited on Search Data Page.

HHEAR-1166 Accept params from HHEAR Portal new Study View Page, Format numbers to use comma separated, Revamp StudyPage

---

app/org/hadatac/console/controllers/Signup.java
app/org/hadatac/console/controllers/dataacquisitionsearch/DataAcquisitionSearch.java
app/org/hadatac/console/controllers/dataacquisitionsearch/Downloader.java
app/org/hadatac/console/controllers/studies/StudyView.java
app/org/hadatac/console/providers/MyUsernamePasswordAuthProvider.java
app/org/hadatac/console/views/dataacquisitionsearch/facetOnlyBrowser.scala.html
app/org/hadatac/console/views/receiver.scala.html
app/org/hadatac/console/views/studies/studyView.scala.html
app/org/hadatac/entity/pojo/Measurement.java
public/javascripts/measurement.js

Revamp Study Page.
Changes to rename download files on the download page.
Accept params from HHEAR Portal new Study View Page to do download, show shiny app.
Update the Generate Dataset Method to Use FacetHandler.
Make frequency comma delimited on Search Data Page.

HHEAR-1348/1166 Changes for HHHEAR Portal Download, Number display format, Revamp Study Page

---

app/org/hadatac/console/views/studies/studyView.scala.html

The fix for the issue where we would have to login twice to HHEAR Portal in order to access HADatAc.
Code to allow the Study View to show the Org Chart and not the Shiny App.

Hhear 1349 debug initial login issue and update study page

---

app/org/hadatac/console/controllers/Application.java
app/org/hadatac/console/controllers/Portal.java
app/org/hadatac/console/controllers/Signup.java
app/org/hadatac/console/views/receiver.scala.html
app/org/hadatac/console/views/studies/studyView.scala.html

- Fixed initial login issue between HHEAR - HaDatAc
- Reverted study view to include only currently available features [Tyrone]

Hhear 1349 debug initial login issue

---

app/org/hadatac/console/views/main.scala.html

Hide login and signup button for third party user

Hide login and signup button for third party user

---

app/org/hadatac/console/views/landingPage.scala.html
conf/hadatac-docker.conf
conf/hadatac.conf

updated SignUp & login links for thirdPartyUsers

updated SignUp & login links for thirdPartyUsers

---

test/src/multiStudyTest/MultiStudyTest.java
test/src/studyTest/StudyTest.java

added missing argument in the test framework

added missing argument in the test framework
